164491979 Implement landing page
andela/ah-frontend-summer pull request #17
Opened 2019-03-14 06:40 UTC by pbkabali

#### Description
- Implement the landing page where users go on first visiting the app site

#### Type of change
- Feature

#### How Has This Been Tested?
- Fetch and check out this branch
- Run `npm install` to install all packages
- Run `npm start` to start the server
- Check the landing page in the browser

#### Checklist:

#### Relevant Pivotal Tracker stories

[164491979](https://www.pivotaltracker.com/story/show/164491979)

2019-03-14 14:25 UTC, missvicki requested changes
Amazing job on getting this done quickly. Could you please reduce on the font or the size of the image in height. I think it is too big

2019-03-15 04:49 UTC, codjoero approved these changes
Great work guys, landing page looks amazing, though, on top of slightly reducing the font size, I wonder if it's by design that the `get started` button stays down after one clicks and hovers away. Shouldn't it come right back up? In any case great work.

2019-03-15 08:52 UTC, oma0256 approved these changes

2019-03-15 08:56 UTC, missvicki approved these changes
thanks for making the changes

2019-03-15 08:59 UTC, collinewait approved these changes

2019-03-15 09:00 UTC, merged