163383137 Implement CRUD Article
andela/ah-frontend-summer pull request #25
Opened 2019-03-20 13:30 UTC by FahdJamy

#### Description
---
1. Users one logged in, they can create articles
##### Screenshot
![image](https://user-images.githubusercontent.com/27225249/54687432-99a6cb00-4b2c-11e9-88b9-99187db962c0.png)
2. Authors of the article can update and delete their articles if they are logged in.
##### Screenshots
![image](https://user-images.githubusercontent.com/27225249/54687526-de326680-4b2c-11e9-95ee-f29b1d1a181b.png)
![image](https://user-images.githubusercontent.com/27225249/54687776-69136100-4b2d-11e9-9e8c-7d0063b2ef48.png)

#### Type of change
---
- New Feature
#### How Has This Been Tested?
---
- Unit tests
#### Relevant Pivotal Tracker stories
---
[163383137](https://www.pivotaltracker.com/story/show/163383137)

2019-03-21 08:41 UTC, karuhanga requested changes
Th `UI looks really good. Thumbs up @FahdJamy.
A few observations;
- I cannot seem to find a button for creating an article on the /articles or home page
- Visiting a `slug` that does not exist just loads for ever
- The endpoint for creating an article is `/articles/new/create`. This does not seem very intuitive
- There are actions in the editor that the app does not support. Could these be removed e.g Image upload?
- Can a user upload an image as they create the article?
- Clicking the create article button twice creates two different articles!

2019-03-21 10:09 UTC, collinewait commented on src/__mocks__/axios.js
> +}
`EOF`

2019-03-21 10:09 UTC, collinewait commented on src/assets/styles/Article.css
> +    /* display: grid;
Commented code.

2019-03-21 10:09 UTC, collinewait commented on src/components/UI/Toast/toast.js
> +import { toast } from 'react-toastify';
Is `UI` directory the proper directory for this file?

2019-03-21 10:09 UTC, collinewait commented on src/components/UI/Article/ArticleForm.jsx
> +        <div className="CreateArticleForm">
I observe a mixture of double and single quotes.

2019-03-21 10:09 UTC, collinewait commented on src/components/UI/Article/ArticleForm.jsx
> +                        {props.formTitle}
We would have used destructuring to limit the number of `props.`. It is also possible to destructure from the function parameter level. `const a = ({b, c, d}) => {}`

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/Article.jsx
> +        if ( window.confirm('Are you sure you want to delete this article?') ) {
We shouldn't use `window`.

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/Article.jsx
> +                    title={this.props.article.title}
We can use destructuring to reduce the occurrence of `this.props` and `this.props.article`

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +        if ((this.state.articleData.body === '' && this.state.articleData.body > 5) || articleData.title === "" || articleData.description === "") {
This line is too long. It has 139 characters. Lines shouldn't exceed 80 characters.
There is a mixture of single quotes and double quotes.

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +        const currentState = {...this.state}
Let us terminate(`;`) our statements.

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +            articleData: articleData,
Since the `key` and `value` are the same. You can use shorthand.

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +        if (articleData.title === "" || articleData.description === "" || articleData.body === "") {
The line is too long. It has `90` characters.

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +        if (e.target.name === 'title') {
We would have factored out `e.target.name`

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +        if (articleData.title !== "") {
The condition (`!==""`) is unnecessary.   `if (articleData.title)`  is enough.
It is the same issue on line 66.

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +            articleData: articleData,
Use shorthand notation where possible.

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/UpdateArticle.jsx
> +        if (articleData.title === "" || articleData.description === "" || articleData.body === "") {
This line is too long.

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/UpdateArticle.jsx
> +        const currentState = {...this.state}
terminate(`;`) statements

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/UpdateArticle.jsx
> +        if ((this.state.articleData.body === '' && this.state.articleData.body < 5) || articleData.title === "" || articleData.description === "") {
The line is too long.

2019-03-21 10:09 UTC, collinewait commented on src/containers/Articles/Article/UpdateArticle.jsx
> +            this.props.history.push("/articles/" + this.props.match.params.slug)
Use string literals.

2019-03-21 17:49 UTC, FahdJamy commented
Thanks for the feedback @Karuhanga and @collinewait.
I have worked on all the feedback you asked me for.

2019-03-21 19:07 UTC, karuhanga approved these changes

2019-03-21 19:08 UTC, Karuhanga commented
Excellent work @FahdJamy.

2019-03-22 05:31 UTC, missvicki approved these changes
LGTM

2019-03-22 06:45 UTC, codjoero approved these changes
@FahdJamy, You my friend pulled a nice one here, great job.

2019-03-22 06:57 UTC, pbkabali approved these changes

2019-03-22 07:07 UTC, collinewait commented on src/assets/styles/Backdrop.css
> +}
EOF

2019-03-22 07:07 UTC, collinewait commented on src/assets/styles/Modal.css
> +}
EOF

2019-03-22 07:07 UTC, collinewait commented on src/store/actions/article.js
> +        dispatch(articleActionStart())
Terminate(`;`) statements.

2019-03-22 07:07 UTC, collinewait commented on src/store/actions/article.js
> +        let token = localStorage.getItem('token')
Terminate(;) statements.

2019-03-22 07:07 UTC, collinewait commented on src/store/actions/article.js
> +            dispatch(deleteArticleAction(response.data))
Terminate(;) statements.

2019-03-22 07:07 UTC, collinewait commented on src/store/actions/article.js
> +            dispatch(actionFinised())
Terminate(;) statements.

2019-03-22 07:08 UTC, collinewait commented
The new changes still have a mixture of single quotes and double quotes.

2019-03-22 08:46 UTC, collinewait commented on src/components/UI/Backdrop/Backdrop.js
> +export default backdrop;
EOF

2019-03-22 08:46 UTC, collinewait commented on src/components/UI/Modal/Modal.js
> +export default Modal;
EOF

2019-03-22 08:47 UTC, collinewait commented on src/assets/styles/Article.css
> +.ArticleBody {
Since we are using sass, file extensions for styles should be `.scss`

2019-03-22 08:59 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +            articleData: articleData,
Haven't improved this yet.

2019-03-22 09:18 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +        const articleData = {...currentState.articleData};
We would have extracted the `body` and `title` with: 
`const {body, title} = ...currentState.articleData`

2019-03-22 09:18 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +        const currentState = {...this.state};
This line isn't necessary. We can access the data directly on line `35` .

2019-03-22 09:18 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +            articleData: articleData,
As if the data, in this case, is identical. Are we updating the state with new data?

2019-03-22 09:23 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +        const articleData = {...currentState.articleData};
It is a repetition on line `35` and it can be made better by extracting exact values need as described in the comment  on line `35`

2019-03-22 09:27 UTC, collinewait commented on src/containers/Articles/Article/CreateArticle.jsx
> +        if (e.target.name === "title") {
We can extract data on `e` with destructuring. `e.target` won't be duplicated and our `if` statements will look cleaner.

2019-03-22 10:35 UTC, collinewait approved these changes

2019-03-22 10:36 UTC, merged